### ISSUE TITLE
Distorted content: inline text-boxes not inlined.

### ISSUE THREAD

**Issue by only-a-ptr** [RigsOfRods/docs.rigsofrods.org#11]
Markdown syntax allow inline code boxing `like this` - mainly intended for code snippets.

However, docs.rigsofrods.org gets this wrong and puts all boxes on separate line.

Example:
* Docs page: http://docs.rigsofrods.org/gameplay/multiplayer-server-setup/#getting-the-source
* Github view: https://github.com/RigsOfRods/docs.rigsofrods.org/blob/gh-pages/gameplay/multiplayer-server-setup.md#getting-the-source

Kudos to @Dogy144 for pointing this out.

**Comment by Michael10055** [comment]
This should be closed now as we've reverted back to the original site design.

**Comment by only-a-ptr** [comment]
@Michael10055 Right, thanks for pointing it out.
