### ISSUE TITLE
Switch to MkDocs

### ISSUE THREAD

**Issue by AnotherFoxGuy** [RigsOfRods/docs.rigsofrods.org#119]
Maybe it would be a good idea to switch to MkDocs, so it would be easier to maintain and use the documentation

### Pros
* Easy installation
* Live preview with auto-reload
* Works on mobile
* Build-in search 

### Cons
* Needs Travis or Netlify to build and deploy

A live version of the MkDocs version can be found here: 
https://rigsofrods-docs.netlify.app/
And the source:
https://github.com/AnotherFoxGuy/ror-docs

**Comment by Zentro** [comment]
I'd think it's best to retain the current design we have, And where would this need to be hosted?

**Comment by AnotherFoxGuy** [comment]
With [netlify](https://www.netlify.com/) you can enable PR previews so you can check the site before merging, but you can also set up Travis to build and push it to the gh-pages branch

**Comment by CuriousMike56** [comment]
So how exactly would I contribute using this? Right now all I have to do is open a bash shell and type `sh StartServer.sh` to test the site locally.

**Comment by AnotherFoxGuy** [comment]
Install MkDocs: https://www.mkdocs.org/#installation
then run `mkdocs serve`

**Comment by AnotherFoxGuy** [comment]
Or just open it in a gitpod: https://www.gitpod.io/#https://github.com/AnotherFoxGuy/ror-docs

**Comment by AnotherFoxGuy** [comment]
Fixed with #141
