### ISSUE TITLE
Many images broken on 'Blender for beginners' page

### ISSUE THREAD

**Issue by DevRain2500** [RigsOfRods/docs.rigsofrods.org#15]
As the title says, there are many images broken on the page located here: http://docs.rigsofrods.org/tools-tutorials/blender-beginner/, and https://github.com/RigsOfRods/docs.rigsofrods.org/blob/gh-pages/tools-tutorials/blender-beginner.md.

Image of page as of 2/13/2017: http://i.imgur.com/XJc2Eqg.jpg

(It also seems that if you click on the broken image, it loads just fine...)

**Comment by Michael10055** [comment]
Fixed in https://github.com/RigsOfRods/docs.rigsofrods.org/commit/24aaeee41b3749ffa84baf0df0ddf4afae71df70
