### ISSUE TITLE
White text on white background in tables and some more minor issues since switching to a dark theme

### ISSUE THREAD

**Issue by MarkROR** [RigsOfRods/docs.rigsofrods.org#165]
I went through all the Docs pages quickly and just made note of a few things that can be improved, I hope this can be of some use and doesn't just come off as me complaining (I would fix these but those would be the ugliest fixes imaginable _a:nth-child(1)_ and would likely break more things )

**All tables on all pages**. e.g. **General controls** near the top of the page, white text in a white table
https://docs.rigsofrods.org/gameplay/controls-config/

![tables2](https://user-images.githubusercontent.com/63402074/108606381-b8193f00-73b1-11eb-8058-79cac312b14b.png)

**Introduction** section at top of page, black text on black background:
https://docs.rigsofrods.org/gameplay/beginners-guide/

Some sub-section headings, black on black:
https://docs.rigsofrods.org/gameplay/general-faq/#1-disable-shadows (1, 2, 3 on there)

Pilcrows (the reverse P next to every heading ¶ that gives us the link to it) - black on black 
https://docs.rigsofrods.org/gameplay/jargon/#player-terms

Yellow warnings and green notes on this page:
https://docs.rigsofrods.org/tools-tutorials/blender-beginner/ 
BUT warnings on this page https://docs.rigsofrods.org/tools-tutorials/blender-mesh-editing/ are fine. Inconsistent, I think only these ones should be used.

https://docs.rigsofrods.org/tools-tutorials/blender-beginner/ page has a lot of headings with [edit] links that no longer work, and the headings aren't shown in the bar on the right, meaning they're just big text, meaning you cannot link to specific sections.

https://docs.rigsofrods.org/vehicle-creation/fileformat-truck/#hydros
in the options section, the labels that say " [ Version 0.36+ ]" are white text on yellow background and hard to read

https://docs.rigsofrods.org/terrain-creation/l3dt-map-making/#introduction
Black text on black background

**Comment by Zentro** [comment]
Thank you for opening the issue here. I'll get a PR out to fix these ASAP.

**Comment by Zentro** [comment]
Closed by #166 thanks to @Max98

**Comment by Max98** [comment]
@MarkROR The warning/Errors boxes problem was already present before the theme edit. They will be fixed soon.
