### ISSUE TITLE
RoR Server Not Working

### ISSUE THREAD

**Issue by bob444-web** [RigsOfRods/docs.rigsofrods.org#185]
Hi, 

I've tried to follow the instructions on the rigs of rods website, but when it connects it gives the following error message. 
Couldn't establish connection. 

Could someone please help? Thanks. 

Bob444-web

**Comment by CuriousMike56** [comment]
Closing as this isn't related to the docs, please create a thread on the [webservices support](https://forum.rigsofrods.org/forums/webservices-support.9/) section of the Forum instead.
