### ISSUE TITLE
archive links in section "mods" are dead

### ISSUE THREAD

**Issue by woagXD** [RigsOfRods/docs.rigsofrods.org#224]
the links in the archives section in mods (specifically the backup of the old repo mods and the VBulletin forums prior to the XenForo switch) have been dead for sometime lately. please update the section to say that the links are dead because it might be misleading to others.

**Comment by CuriousMike56** [comment]
Resolved by https://github.com/RigsOfRods/docs.rigsofrods.org/commit/bf622ebd556385bc55fa560fa18c3ceab56a1410
