### ISSUE TITLE
Absolute link errors

### ISSUE THREAD

**Issue by Zentro** [RigsOfRods/docs.rigsofrods.org#227]
Getting an output like:
```INFO    -  Doc file 'vehicle-creation/suspension.md' contains an absolute link '/vehicle-creation/fileformat-truck#shocks', it was left as is. Did you mean 'fileformat-truck.md#shocks'?```

Which is clogging the console log/output. These links need to be fixed.

**Comment by CuriousMike56** [comment]
These warnings were introduced in a recent MkDocs update. I'll look into fixing them once the new layout is merged.
