### ISSUE TITLE
Page hierarchy

### ISSUE THREAD

**Issue by only-a-ptr** [RigsOfRods/docs.rigsofrods.org#53]
Currently, there are 3 separate hierarchies in place:
 1. Directory structure - 4 directories: "gameplay", "vehicle-creation", "terrain-creation" and "tools-tutorials". These have no technical meaning, the web would work just the same if they were in a single directory.
 2. `categories: []` entry in the pages. These are just labels, there's no automated mechanism associated with them. We currently use them to sort links on the homepage, but this is not a requirement.
 3. Homepage sections. Although they correspond to `categories:` and the directory structure, they're not related. The titles are hardcoded in the homepage's source and `categories` to display are manually specified there as well.

Problem: The (1.) directory structure shows in page URLs. This means moving page to different (possibly new) category breaks outside links to the docs. We want the flexibility to reorganize pages without breaking outside links.

Solution: wiki-style; we need the URLs to display without any hierarchy in it, like MediaWiki does it. The simple way to do this is to just move all page files (.md) files to the root directory.

**Comment by Michael10055** [comment]
I'm all for this, but one problem: If we remove the hierarchy from the URL then all outside links to the docs will break (again), I'd like to avoid this.

**Comment by only-a-ptr** [comment]
Please try this: https://help.github.com/articles/redirects-on-github-pages/

**Comment by Michael10055** [comment]
I'm not sure if I want this now that I've moved everything to the root directory - It makes the directory messy and even more of a PITA to edit.
![image](https://user-images.githubusercontent.com/11002490/34071884-b67aaf44-e24b-11e7-855c-a7591b81fcf6.png)

**Comment by only-a-ptr** [comment]
> We need to come up with a better solution.
Allright, that's a mess, but perhaps a single 'pages' directory (with only doc pages) would do? Provided that you switch your file browser to a more usable view - I sort files in a directory by extension most of the time.

> ...even more of a PITA to edit.

Sounds like you're not thrilled by using this Jekyll/GH-pages arrangement altogether. I admit it sucks in more than one way (linux, ruby...), but I'd still take it over MediaWiki anytime:
* I no longer have to copypaste text to an editor for editing code/config samples.
* To preview, you just switch to browser window and refresh. scrolling stays in place. In MW, you scroll usually 3 times - to find your change in page, to go back to edit window, to find your change in edit window.

**Comment by Michael10055** [comment]
I'm going to close this as there's really nothing wrong with the current directory setup (plus I wasn't able to get `jekyll-redirect-from` working). Editing has become a lot easier now that I've got Jekyll setup on Windows. :smile:
