### ISSUE TITLE
[Info Request] How to contribute to this?

### ISSUE THREAD

**Issue by DevRain2500** [RigsOfRods/docs.rigsofrods.org#9]
How would I go about properly contributing to the docs? Is there a format/template to follow? Or has that not been established yet? Any advice would be appreciated. :)

**Comment by only-a-ptr** [comment]
Hello @Dogy144 

My bad, a contribution guide is badly due. I'll write down a draft right here to have at least something.

# Contribution guide (draft)

The documentation is maintained as a suite of Markdown documents with a Jekyll project to generate webpages from it, and Git is used to manage revision history.

Advantages: Comfortable to edit (use text editor of your choice) and preview (use `jekyll --serve` to start local server and view changes in browser). Paired with GitHub and GitHub-pages, it works similar to Wiki.
Provides greater freedom of content publishing/localization/special features (you have direct control of code).

Disadvantages: Complicated for non-technical users, the Jekyll tool is linux-only.

Reasons: Comfort for dedicated authors was preffered over comfort of contributors. Traditional Wikis all use in-browser editing, which is simple to use for everybody but annoying to use for matter experts who work with whole pages and do cleanups. Especially MediaWiki's interface is stone-age and PITA to work with.

## How to contribute

The most important contribution is feedback to documentation authors. If you have any problem/question/suggestion, get in touch. Use the [GitHub issue tracker](https://github.com/RigsOfRods/docs.rigsofrods.org/issues) for this. Alternatively, you can get in touch with RoR developers and webmasters/maintainers on other channels (forum/Gitter/Discord...)

Second, you may want to edit existing pages (fix bad links, add notes or delete misleading bits). You can either do the editing yourself or report the issue/suggestion and let documentation staff handle it.

Finally, you'll want to add new pages. In this case, first consider fitting your information into existing pages. The old RoR wiki was full of separate tutorials duplicating the basic info and carrying little added value. We want to keep related info together and maintain reasonable amout of pages. To actually add your page, you can work with Git/text editor yourself or post a draft of your document to issue tracker/forum and get help from a maintainer.

## The simplest editing - GitHub interface

To do minor edits of pages (fixing bad links, adding info), you can use GitHub web interface. Each doc page contains an "edit on GitHub" link - it will take you to GitHub where you can edit and preview the page. When you're done and save your changes, GitHub will create a "pull request" (alias PR) which is a pending update. This update needs to be reviewed and accepted (pulled) by docs staff.

## Your own workplace - Fork the docs

*** to be written ***

help: https://help.github.com/
tip: https://help.github.com/articles/fork-a-repo/

## Advanced editing - Work offline

*** to be written ***

Linux setup needed.

**Comment by wilkgr76** [comment]
On the [TODO list](http://docs.rigsofrods.org/oldwiki-todo/), does 'pending' mean someone is already working on it?

**Comment by only-a-ptr** [comment]
@wilkgr76 This is a very good place to ask, thanks for posting, it brings the docs back to my attention.

The 'pending' section is pretty much my note-to-self; it means I already looked at the source page and found it meaningful to process. But it's out of date, I haven't worked on the docs in a year or so.

**Comment by wilkgr76** [comment]
So basically- I can (try) to move these to the new documentation and make a PR?

**Comment by DevRain2500** [comment]
Yes

**Comment by only-a-ptr** [comment]
> @wilkgr76 So basically- I can (try) to move these to the new documentation and make a PR?

Absolutely. And feel free to update the TODO/DONE pages where you see fit. I should have put a 'contributors welcome' banner on there :)
